# general
seed: 4 # run seed

# coding hyperparams
blocks_num: 36 # number of validation frames. values: int.
code_type: 'BCH' # ['BCH','POLAR']
code_bits: 63
message_bits: 36
decoder_type: 'hard_bp' # ['bp','wbp','hd','hard_bp']

# datasets
channel_model: 'BSC' # ['AWGN','BSC']
snr: 8 # validation snr value. values: float.
modulation_type: 'BPSK' # ['BPSK','QPSK','EightPSK']
p: 0.01