# general
seed: 4 # run seed

# coding hyperparams
blocks_num: 100 # number of validation frames. values: int.
code_type: 'BCH' # ['BCH','POLAR']
code_bits: 127
message_bits: 64
decoder_type: 'hard_wbp' # ['bp','wbp','hd','hard_bp','hard_wbp']

# datasets
channel_model: 'BSC' # ['AWGN','BSC']
snr: 8 # validation snr value. values: float.
modulation_type: 'BPSK' # ['BPSK','QPSK','EightPSK']
p: 0.005